workflow:
  name: Exploring Gitlab CI Concepts
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      variables:
        DEPLOY_VARIABLE: PRODUCTION

deploy_job:
  resource_group: production
  parallel:
    matrix:
      - RUNNER_MACHINES:
          - saas-linux-small-amd64
          - saas-linux-medium-amd64
        NODE_TAGS:
          - '20-alpine3.19'
          - '21-alpine3.19'
          - '22-alpine3.19'
  tags:
    - $RUNNER_MACHINES 
  image: node:$NODE_TAGS
    - node -v
    - npm -v
